INSERT INTO chatpion.messenger_bot (user_id,page_id,fb_page_id,template_type,bot_type,keyword_type,keywords,message,conditions,message_condition_false,buttons,images,audio,video,file,status,bot_name,postback_id,last_replied_at,is_template,broadcaster_labels,drip_campaign_id,visual_flow_type,media_type,visual_flow_campaign_id,trigger_matching_type) VALUES
	 (1,28,'109340945136513','text','generic','post-back','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text_with_buttons","attachment":{"type":"template","payload":{"template_type":"button","text":"You have been successfully unsubscribed from our list. It is sad to see you go. It is not the same without you! You can join back by clicking the button below.","buttons":[{"type":"postback","payload":"RESUBSCRIBE_QUICK_BOXER","title":"Resubscribe"}]}}}}}','','','','','','','','1','UNSUBSCRIBE BOT','UNSUBSCRIBE_QUICK_BOXER','0000-00-00 00:00:00','1','',0,'flow','fb',197,'exact'),
	 (1,28,'109340945136513','text','generic','post-back','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text_with_buttons","attachment":{"type":"template","payload":{"template_type":"button","text":"Welcome back! We have not seen you for a while. You will no longer miss our important updates.","buttons":[{"type":"postback","payload":"UNSUBSCRIBE_QUICK_BOXER","title":"Unsubscribe"}]}}}}}','','','','','','','','1','RESUBSCRIBE BOT','RESUBSCRIBE_QUICK_BOXER','0000-00-00 00:00:00','1','',0,'flow','fb',198,'exact'),
	 (1,28,'109340945136513','text','generic','email-quick-reply','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text","text":"Thanks, we have received your email. We will keep you updated. Thank you for being with us."}}}','','','','','','','','1','QUICK REPLY EMAIL REPLY','QUICK_REPLY_EMAIL_REPLY_BOT','0000-00-00 00:00:00','0','',0,'flow','fb',199,'exact'),
	 (1,28,'109340945136513','text','generic','phone-quick-reply','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text","text":"Thanks, we have received your phone number. We will keep you updated. Thank you for being with us."}}}','','','','','','','','1','QUICK REPLY PHONE REPLY','QUICK_REPLY_PHONE_REPLY_BOT','0000-00-00 00:00:00','0','',0,'flow','fb',200,'exact'),
	 (1,28,'109340945136513','text','generic','location-quick-reply','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text","text":"Thanks, we have received your location. Thank you for being with us."}}}','','','','','','','','1','QUICK REPLY LOCATION REPLY','QUICK_REPLY_LOCATION_REPLY_BOT','0000-00-00 00:00:00','0','',0,'flow','fb',201,'exact'),
	 (1,28,'109340945136513','text','generic','birthday-quick-reply','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text","text":"Thanks, we have received your birthday. Thank you for being with us."}}}','','','','','','','','1','QUICK REPLY BIRTHDAY REPLY','QUICK_REPLY_BIRTHDAY_REPLY_BOT','0000-00-00 00:00:00','0','',0,'flow','fb',202,'exact'),
	 (1,28,'109340945136513','text','generic','post-back','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text_with_buttons","attachment":{"type":"template","payload":{"template_type":"button","text":"Thanks! It is a pleasure talking to you. One of our team members will reply to you soon. If you want to chat with me again, just click the button below.","buttons":[{"type":"postback","payload":"YES_START_CHAT_WITH_BOT","title":"Resume Chat with Bot"}]}}}}}','','','','','','','','1','CHAT WITH HUMAN','YES_START_CHAT_WITH_HUMAN','0000-00-00 00:00:00','1','',0,'flow','fb',203,'exact'),
	 (1,28,'109340945136513','text','generic','post-back','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text_with_buttons","attachment":{"type":"template","payload":{"template_type":"button","text":"I am glad to have you back. I will try my best to answer all questions. If you want to start chatting with humans again you can simply click the button below.","buttons":[{"type":"postback","payload":"YES_START_CHAT_WITH_HUMAN","title":"Chat with human"}]}}}}}','','','','','','','','1','CHAT WITH BOT','YES_START_CHAT_WITH_BOT','0000-00-00 00:00:00','1','',0,'flow','fb',204,'exact'),
	 (1,28,'109340945136513','text','generic','get-started','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text","text":"Hi #LEAD_USER_FIRST_NAME#, Welcome to our page."}}}','','','','','','','','1','GET STARTED','','0000-00-00 00:00:00','0','',0,'flow','fb',205,'exact'),
	 (1,28,'109340945136513','text','generic','no match','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text","text":"Sorry, we could not find any content to show. One of our team members will reply to you soon."}}}','','','','','','','','1','NO MATCH FOUND','','0000-00-00 00:00:00','0','',0,'flow','fb',206,'exact');
INSERT INTO chatpion.messenger_bot (user_id,page_id,fb_page_id,template_type,bot_type,keyword_type,keywords,message,conditions,message_condition_false,buttons,images,audio,video,file,status,bot_name,postback_id,last_replied_at,is_template,broadcaster_labels,drip_campaign_id,visual_flow_type,media_type,visual_flow_campaign_id,trigger_matching_type) VALUES
	 (1,28,'109340945136513','text','generic','no match','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":"0","text_reply_unique_id":"EKp6WxW7lHlVDBK","template_type":"text","text":"Sorry, we could not find any content to show. One of our team members will reply to you soon."}}}','','','','','','','','1','NO MATCH FOUND','','0000-00-00 00:00:00','0','',0,'flow','ig',207,'exact'),
	 (1,28,'109340945136513','text','generic','story-mention','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":0,"text_reply_unique_id":"HjKksxHRQtGc7hq","template_type":"text","text":"Thanks for mentioning me."}}}','','','','','','','','1','STORY MENTION','STORY_MENTION','0000-00-00 00:00:00','0','',0,'flow','ig',208,'exact'),
	 (1,28,'109340945136513','text','generic','story-private-reply','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":0,"text_reply_unique_id":"HjKksxHRQtGc7hq","template_type":"text","text":"Thanks for your comment on my story."}}}','','','','','','','','1','STORY PRIVATE REPLY','STORY_PRIVATE_REPLY','0000-00-00 00:00:00','0','',0,'flow','ig',209,'exact'),
	 (1,28,'109340945136513','text','generic','message-unsend-private-reply','','{"1":{"recipient":{"id":"replace_id"},"message":{"typing_on_settings":"off","delay_in_reply":0,"text_reply_unique_id":"HjKksxHRQtGc7hq","template_type":"text","text":"As you have deleted your message, we want to ensure you that our bot does not save any of your messages. So it will not be saved in our bot. Thanks"}}}','','','','','','','','1','MESSAGE UNSEND PRIVATE REPLY','MESSAGE_UNSEND_PRIVATE_REPLY','0000-00-00 00:00:00','0','',0,'flow','ig',210,'exact');
